---
- name: install nodejs (1/2)
  shell: "curl -sL https://deb.nodesource.com/setup_5.x | bash -"

- name: install nodejs (2/2)
  apt:
    name: nodejs
    state: present
    update_cache: yes

#- name: Install packages based on package.json.
#  npm: path=/vagrant global=yes
#  sudo: yes

- name: install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - pm2
    - bower
    - express
    - socket.io


