---
- name: apt-get update
  apt: update_cache=yes

- name: install tools
  apt: name={{ item }}
  with_items:
   - git
   - htop
   - vim
   - nano
   - openssl
   - python-software-properties
   - software-properties-common
   - curl
  notify: update apt


